version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: production
    command:
      - "npm"
      - "run"
      - "start"
    environment:
      NODE_ENV: "production"
    restart: "always"
    ports:
      - "3000:3000"
